branch-defaults:
  back:
    environment: flask-env
  default:
    environment: flask-env
    group_suffix: null
  master:
    environment: flask-env
    group_suffix: null
environment-defaults:
  Pachuling-env:
    branch: null
    repository: null
  flask-env:
    branch: null
    repository: null
global:
  application_name: pachuling
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
